# Generated by Django 3.2.6 on 2021-08-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=50, max_digits=100)),
                ('process_charge', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=50, max_digits=100)),
                ('latitude', models.DecimalField(decimal_places=50, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('facilities', models.CharField(blank=True, max_length=200, null=True)),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
                ('landmarks', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.categories')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.map')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.contact')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, unique=True)),
                ('policies', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.usertype'),
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.categories')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nijiapp.subcategories'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='Image_Gallery')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
            ],
        ),
    ]
