# Generated by Django 3.2 on 2021-11-20 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=50, max_digits=100)),
                ('process_charge', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=50, max_digits=100)),
                ('latitude', models.DecimalField(decimal_places=50, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
                ('landmarks', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100)),
                ('thumbnail', models.ImageField(upload_to='Image_Gallery/thumbnail')),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('parking', models.CharField(blank=True, max_length=100, null=True)),
                ('kitchen', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('builtup_area', models.CharField(blank=True, max_length=100, null=True)),
                ('road_access', models.CharField(blank=True, max_length=100, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.map')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_verified', models.BooleanField(default=False)),
                ('counter', models.BigIntegerField(default=1)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.propertytype'),
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name=' Verification Code ')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=' Generation time ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='Image_Gallery')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nijiapp.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('False', 'No'), ('True', 'Yes')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercontact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
