# Generated by Django 2.2.20 on 2022-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Karnali Province', 'karnali province'), ('Province No. 1', 'province no 1'), ('Bagmati Province', 'bagmati province'), ('Lumbini Province', 'lumbini province'), ('Province No. 2', 'province no 2'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Gandaki Province', 'gandaki province')], max_length=200),
        ),
    ]
