# Generated by Django 3.2 on 2021-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0002_alter_properties_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100),
        ),
    ]
