# Generated by Django 2.2.20 on 2022-01-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0002_auto_20220111_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='property',
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nijiapp.PropertyType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('Manager', 'manager'), ('CEO', 'ceo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Bagmati Province', 'bagmati province'), ('Lumbini Province', 'lumbini province'), ('Province No. 2', 'province no 2'), ('Karnali Province', 'karnali province'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Province No. 1', 'province no 1'), ('Gandaki Province', 'gandaki province')], max_length=200),
        ),
    ]
