# Generated by Django 3.2.6 on 2021-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0002_auto_20210911_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='property_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100),
        ),
    ]
