# Generated by Django 3.2 on 2021-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0003_auto_20211120_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='position',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
