# Generated by Django 3.2.6 on 2021-09-26 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nijiapp', '0004_auto_20210916_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Buy', 'buy'), ('Rent', 'rent')], max_length=100),
        ),
    ]
