# Generated by Django 2.2.20 on 2021-12-24 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0006_auto_20211224_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='properties',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Gandaki Province', 'gandaki province'), ('Karnali Province', 'karnali province'), ('Province No. 1', 'province no 1'), ('Lumbini Province', 'lumbini province'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Province No. 2', 'province no 2'), ('Bagmati Province', 'bagmati province')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Buy', 'buy'), ('Rent', 'rent')], max_length=100),
        ),
    ]
