# Generated by Django 2.2.20 on 2021-12-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0007_auto_20211224_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Province No. 1', 'province no 1'), ('Karnali Province', 'karnali province'), ('Gandaki Province', 'gandaki province'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Bagmati Province', 'bagmati province'), ('Lumbini Province', 'lumbini province'), ('Province No. 2', 'province no 2')], max_length=200),
        ),
    ]
