# Generated by Django 2.2.20 on 2021-12-25 16:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0008_auto_20211225_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='Image_Gallery/about_company')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='Image_Gallery/card')),
                ('position', models.CharField(choices=[('CEO', 'ceo'), ('Manager', 'manager')], max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Buy', 'buy'), ('Rent', 'rent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Lumbini Province', 'lumbini province'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Province No. 1', 'province no 1'), ('Bagmati Province', 'bagmati province'), ('Province No. 2', 'province no 2'), ('Karnali Province', 'karnali province'), ('Gandaki Province', 'gandaki province')], max_length=200),
        ),
    ]
