# Generated by Django 2.2.20 on 2022-01-10 09:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0009_auto_20211225_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='user_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Sudurpashchim Province', 'sudurpashchim province'), ('Province No. 1', 'province no 1'), ('Karnali Province', 'karnali province'), ('Gandaki Province', 'gandaki province'), ('Province No. 2', 'province no 2'), ('Lumbini Province', 'lumbini province'), ('Bagmati Province', 'bagmati province')], max_length=200),
        ),
    ]
