# Generated by Django 3.2 on 2021-10-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nijiapp', '0009_auto_20211024_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('False', 'No'), ('True', 'Yes')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
