# Generated by Django 2.2.20 on 2022-01-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0010_auto_20220110_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='map',
        ),
        migrations.AddField(
            model_name='map',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='nijiapp.Properties'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('False', 'No'), ('True', 'Yes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Sudurpashchim Province', 'sudurpashchim province'), ('Bagmati Province', 'bagmati province'), ('Karnali Province', 'karnali province'), ('Province No. 1', 'province no 1'), ('Lumbini Province', 'lumbini province'), ('Province No. 2', 'province no 2'), ('Gandaki Province', 'gandaki province')], max_length=200),
        ),
    ]
