# Generated by Django 2.2.20 on 2022-01-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0011_auto_20220110_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='property_type',
        ),
        migrations.AddField(
            model_name='propertytype',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ptype', to='nijiapp.Properties'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('Manager', 'manager'), ('CEO', 'ceo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Bagmati Province', 'bagmati province'), ('Sudurpashchim Province', 'sudurpashchim province'), ('Province No. 1', 'province no 1'), ('Lumbini Province', 'lumbini province'), ('Karnali Province', 'karnali province'), ('Gandaki Province', 'gandaki province'), ('Province No. 2', 'province no 2')], max_length=200),
        ),
    ]
