# Generated by Django 3.2 on 2021-10-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0011_alter_properties_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Rent', 'rent'), ('Buy', 'buy')], max_length=100),
        ),
    ]
