# Generated by Django 2.2.20 on 2022-01-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nijiapp', '0013_auto_20220110_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='property',
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nijiapp.PropertyType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='property',
            field=models.CharField(choices=[('Buy', 'buy'), ('Rent', 'rent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='province',
            field=models.CharField(choices=[('Sudurpashchim Province', 'sudurpashchim province'), ('Lumbini Province', 'lumbini province'), ('Karnali Province', 'karnali province'), ('Gandaki Province', 'gandaki province'), ('Province No. 2', 'province no 2'), ('Province No. 1', 'province no 1'), ('Bagmati Province', 'bagmati province')], max_length=200),
        ),
    ]
